# fly.toml app configuration file generated for pong-multiplayer on 2024-03-12T14:29:30+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pong-multiplayer'
primary_region = 'cdg'

[build]
  [build.args]
    GO_VERSION = '1.22.1'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
